[package]
name = "moko-domain"
version = "0.1.0"
authors = ["mofu"]
edition = "2018"

[dependencies]
anyhow = "*"
chrono = "0.4.10"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
