[package]
name = "moko-migration"
version = "0.1.0"
authors = ["mofu"]
edition = "2018"

[dependencies]
barrel = { version = "0.6.5", features = ["sqlite3"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
